name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No changes'

categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - fix
      - bugfix
      - bug
  - title: '🧰 Maintenance'
    labels:
      - chore
      - refactor
      - ci
      - documentation
      - dependencies

exclude-labels:
  - skip-changelog

template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: documentation
    files:
      - '*.md'
    title:
      - '/(docs|doc:|\[doc\]|typos|comment|documentation)/i'
  - label: bug
    title:
      - '/(fix|race|bug|missing|correct)/i'
  - label: dependencies
    title:
      - '/(bump|dependencies)/i'
  - label: feature
    title:
      - '/(feature|feat|add)/i'
  - label: refactor
    title:
      - '/^(refactor)(\(.+\))?:/i'
  - label: test
    title:
      - '/^(test|tests)(\(.+\))?:/i'
  - label: ci
    files:
      - '.github/**'

version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - feature
      - enhancement
  patch:
    labels:
      - fix
      - bugfix
      - bug
      - chore
      - refactor
      - documentation
      - ci
      - dependencies
  default: patch
